### PR TITLE
Add vendored packages to RPM

### PR DESCRIPTION
**Pull request by matyasselmeci**
Add a script to create a "-vendor" tarball containing all the vendored-in dependencies (picojson and inih) and use it in the .spec file (except on Fedora, which already has RPMs for those dependencies).

### CODE REVIEW

**Comment by matyasselmeci** [comment]
If you're not a big fan of that solution, we could also use the GitHub release for picojson and the downloadable zip file (https://github.com/jtilly/inih/archive/master.zip) for inih as sources in the spec file.

**Comment by matyasselmeci** [comment]
Note that this doesn't actually work, it just builds. The test is missing `scitokens-admin-create-key`. https://travis-ci.org/matyasselmeci/xrootd-scitokens/builds/529529431

**Comment by matyasselmeci** [comment]
Replaced this by copying in the vendored code and adding a README.vendor with the sources.

**Review by bbockelm — APPROVED** [review]
LGTM.

**Pull request merged**
